// js/config/jokes-data.js
// --- SCHOOL LOGO SVG (Using the one based on your image) ---
// const schoolLogoSvg = '<svg viewBox="0 0 450 150" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%"><title>World Compass Academy Logo</title><path d="M75 25 A50 50 0 1 1 75 125" stroke="#007ABF" stroke-width="12" fill="none" transform="rotate(-15 65 75)"/><path d="M65 105 Q60 80 65 55 C65 55 62 50 58 52" fill="#6A4028" stroke="#50301E" stroke-width="1"/><path d="M58 52 Q40 45 50 25 Q60 48 58 52 Z" fill="#8BC34A" stroke="#558B2F" stroke-width="0.5"/><path d="M58 52 Q35 60 45 35 Q60 52 58 52 Z" fill="#AED581" stroke="#558B2F" stroke-width="0.5"/><path d="M58 52 Q45 70 55 45 Q65 55 58 52 Z" fill="#9CCC65" stroke="#558B2F" stroke-width="0.5"/><text x="160" y="60" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="bold" fill="#333333">WORLD</text><text x="130" y="105" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="bold" fill="#333333">COMPASS</text><text x="280" y="135" font-family="Comic Sans MS, Brush Script MT, cursive" font-size="30" fill="#8BC34A" font-style="italic">Academy</text></svg>';
// --- JOKE DATA ---
const dadJokes = [
    { setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts." },
    { setup: "What do you call fake spaghetti?", punchline: "An impasta!" },
    { setup: "Why did the scarecrow win an award?", punchline: "Because he was outstanding in his field!" },
    { setup: "What concert costs just 45 cents?", punchline: "50 Cent featuring Nickelback!" },
    { setup: "Why did the bicycle fall over?", punchline: "Because it was two-tired!" },
    { setup: "How does a penguin build its house?", punchline: "Igloos it together." },
    { setup: "What do you call a fish with no eyes?", punchline: "Fsh!" },
    { setup: "Why can't you hear a pterodactyl go to the bathroom?", punchline: "Because the 'P' is silent." },
    { setup: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
    { setup: "Why did the math book look so sad?", punchline: "Because it had too many problems." },
    { setup: "I'm reading a book about anti-gravity.", punchline: "It's impossible to put down!" },
    { setup: "What do you call a lazy kangaroo?", punchline: "Pouch potato." },
    { setup: "Why don't eggs tell jokes?", punchline: "They'd crack each other up." },
    { setup: "What's brown and sticky?", punchline: "A stick!" },
    { setup: "Why was the cookie sad?", punchline: "Because its mom was a wafer too long!" },
    { setup: "What did the ocean say to the beach?", punchline: "Nothing, it just waved." },
    { setup: "Why are ghosts bad liars?", punchline: "Because you can see right through them." },
    { setup: "What do you call a cheese that isn't yours?", punchline: "Nacho cheese!" },
    { setup: "What kind of tree fits in your hand?", punchline: "A palm tree!" },
    { setup: "How do you organize a space party?", punchline: "You planet." },
    { setup: "Did you hear about the restaurant on the moon?", punchline: "I heard the food was good but it had no atmosphere." },
    { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
    { setup: "What do you call a dog magician?", punchline: "A labracadabrador." },
    { setup: "Why did the old man fall in a well?", punchline: "Because he couldn’t see that well!" },
    { setup: "What do you call a belt made out of watches?", punchline: "A waist of time." },
    { setup: "Why was the baby strawberry crying?", punchline: "Because his parents were in a jam!" },
    { setup: "What do you call an alligator in a vest?", punchline: "An investigator." },
    { setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one." },
    { setup: "What do you get when you cross a snowman and a dog?", punchline: "Frostbite." },
    { setup: "Why can't a nose be 12 inches long?", punchline: "Because then it would be a foot." },
    { setup: "What’s an astronaut’s favorite part of a computer?", punchline: "The space bar." },
    { setup: "Why did the coffee file a police report?", punchline: "It got mugged." },
    { setup: "How do you make a Kleenex dance?", punchline: "Put a little boogie in it!" },
    { setup: "What do you call a sad strawberry?", punchline: "A blueberry." },
    { setup: "Why are pirates called pirates?", punchline: "Because they arrrr!" },
    { setup: "What kind of shoes do ninjas wear?", punchline: "Sneakers." },
    { setup: "What time did the man go to the dentist?", punchline: "Tooth hurt-y." },
    { setup: "Why did the tomato blush?", punchline: "Because it saw the salad dressing!" },
    { setup: "What do you call a cow with no legs?", punchline: "Ground beef." },
    { setup: "Why are elevator jokes so good?", punchline: "They work on many levels." },
    { setup: "What do you call a sleeping bull?", punchline: "A bulldozer." },
    { setup: "What has ears but cannot hear?", punchline: "A cornfield." },
    { setup: "Why don't some couples go to the gym?", punchline: "Because some relationships don't work out." },
    { setup: "What’s brown and sounds like a bell?", punchline: "Dung!" },
    { setup: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
    { setup: "Why did the Invisible Man turn down the job offer?", punchline: "He couldn't see himself doing it." },
    { setup: "How do you catch a squirrel?", punchline: "Climb a tree and act like a nut!" },
    { setup: "What did the grape say when it got stepped on?", punchline: "Nothing, it just let out a little wine." },
    { setup: "Why did the picture go to jail?", punchline: "It was framed." },
    { setup: "What do you call a pile of cats?", punchline: "A meowtain." },
    { setup: "Why did the student eat his homework?", punchline: "Because the teacher said it was a piece of cake." },
    { setup: "What do you call a man with a rubber toe?", punchline: "Roberto." },
    { setup: "Why are fish so smart?", punchline: "Because they live in schools." },
    { setup: "What's a pirate's favorite letter of the alphabet?", punchline: "You'd think it's R, but it's the C they love!" },
    { setup: "Why did the can crusher quit his job?", punchline: "It was soda pressing." },
    { setup: "How do you make holy water?", punchline: "You boil the hell out of it." },
    { setup: "What's orange and sounds like a parrot?", punchline: "A carrot." },
    { setup: "What do you call a group of musical whales?", punchline: "An orca-stra." },
    { setup: "Why did the fungi leave the party?", punchline: "There wasn't mushroom." },
    { setup: "What do you call a boomerang that won't come back?", punchline: "A stick." },
    { setup: "Why was the belt arrested?", punchline: "For holding up a pair of pants!" },
    { setup: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
    { setup: "How do you follow Will Smith in the snow?", punchline: "You follow the fresh prints." },
    { setup: "Why did the psychic refuse to pay his exorcist?", punchline: "He said he'd seen it coming." },
    { setup: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
    { setup: "Why did the bee get married?", punchline: "Because he found his honey." },
    { setup: "What’s the best thing about Switzerland?", punchline: "I don’t know, but the flag is a big plus." },
    { setup: "What do you call a cow that plays an instrument?", punchline: "A moo-sician." },
    { setup: "Why did the clock go to the library?", punchline: "It wanted to check out the time." },
    { setup: "What kind of car does an egg drive?", punchline: "A Yolkswagen." },
    { setup: "Why was the broom late?", punchline: "It over-swept." },
    { setup: "What do you call a short, psychic dwarf who has escaped from prison?", punchline: "A small medium at large." },
    { setup: "Why do we tell actors to 'break a leg?'", punchline: "Because every play has a cast." },
    { setup: "What did the left eye say to the right eye?", punchline: "Between you and me, something smells." },
    { setup: "What do you call a lazy baby kangaroo?", punchline: "Pouch potato!" },
    { setup: "Why did the chewing gum cross the road?", punchline: "It was stuck to the chicken's foot." },
    { setup: "What do you call a thieving alligator?", punchline: "A crook-o-dile." },
    { setup: "Why couldn't the leopard play hide and seek?", punchline: "Because he was always spotted." },
    { setup: "What kind of music do mummies listen to?", punchline: "Wrap music." },
    { setup: "Why did the man put his money in the blender?", punchline: "He wanted to make liquid assets." },
    { setup: "What’s a foot long and slippery?", punchline: "A slipper!" },
    { setup: "What do you call a fish with a crown?", punchline: "A kingfish." },
    { setup: "Why did the singer bring a ladder to her concert?", punchline: "She wanted to reach the high notes." },
    { setup: "What do you call a nosy pepper?", punchline: "Jalapeño business!" },
    { setup: "Why did the gardener plant a light bulb?", punchline: "He wanted to grow a power plant!" },
    { setup: "What do you call a funny mountain?", punchline: "Hill-arious." },
    { setup: "Why did the banana go to the doctor?", punchline: "It wasn't peeling well." },
    { setup: "What do you call a chicken staring at a lettuce?", punchline: "Chicken sees a salad." },
    { setup: "What did the zero say to the eight?", punchline: "Nice belt!" },
    { setup: "Why did the computer go to the doctor?", punchline: "It had a virus." },
    { setup: "What has four wheels and flies?", punchline: "A garbage truck." },
    { setup: "Why was the math book sad?", punchline: "It had too many problems." },
    { setup: "What do you call a pig that does karate?", punchline: "A pork chop." },
    { setup: "Why did the baker stop making donuts?", punchline: "He got tired of the hole business." },
    { setup: "What do you call a group of disorganized cats?", punchline: "A cat-tastrophe." },
    { setup: "Why did the chicken join a band?", punchline: "Because it had the drumsticks." },
    { setup: "What do you call a horse that lives next door?", punchline: "A neigh-bor." },
    { setup: "Why did the scarecrow become a successful motivational speaker?", punchline: "He was outstanding in his field." },
    { setup: "What's a vampire's favorite fruit?", punchline: "A neck-tarine." },
    { setup: "Why did the student bring a ladder to school?", punchline: "To go to high school." },
    { setup: "What do you call a droid that takes the long way around?", punchline: "R2-Detour." },
    { setup: "Why did the bicycle stand up by itself?", punchline: "It was two tired." },
    { setup: "What do you call an elephant that doesn’t matter?", punchline: "An irrelephant." },
    { setup: "What is a pirate's favorite subject?", punchline: "Arrrrrrt!" },
    { setup: "Why did the chef get arrested?", punchline: "For beating an egg." },
    { setup: "What do you call a sleeping dinosaur?", punchline: "A Dinosnore." },
    { setup: "Why are teddy bears never hungry?", punchline: "They are always stuffed." },
    { setup: "What do you call a dog that can tell time?", punchline: "A watchdog." },
    { setup: "Why was the stadium so cold?", punchline: "It was full of fans." },
    { setup: "What do you call a fly without wings?", punchline: "A walk." },
    { setup: "Why did the man get fired from the calendar factory?", punchline: "He took a couple of days off." },
    { setup: "What do you call a deer with no eyes?", punchline: "No eye-deer." },
    { setup: "What do you call a deer with no eyes and no legs?", punchline: "Still no eye-deer." },
    { setup: "Why was the photographer so bad at his job?", punchline: "He couldn't focus." },
    { setup: "What do you call a wizard who is good at cooking?", punchline: "A saucier." },
    { setup: "Why did the king go to the dentist?", punchline: "To get his teeth crowned." },
    { setup: "What do you call a sad cup of coffee?", punchline: "Depresso." },
    { setup: "Why did the barber win the race?", punchline: "He knew a shortcut." },
    { setup: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
    { setup: "Why don't oysters donate to charity?", punchline: "Because they are shellfish." },
    { setup: "What do you call a fake noodle?", punchline: "An impasta." },
    { setup: "Why was the little ink drop crying?", punchline: "Because its mother was in the pen and it didn't know how long the sentence would be." },
    { setup: "What do you call a line of rabbits walking backwards?", punchline: "A receding hare-line." },
    { setup: "Why did the football coach go to the bank?", punchline: "To get his quarter back." },
    { setup: "How much did the pirate pay for his corn?", punchline: "A buck an ear!" },
    { setup: "What's a pirate's favorite kind of fish?", punchline: "A swordfish, of course!" },
    { setup: "Why don't pirates shower before they walk the plank?", punchline: "Because they'll just wash up on shore later!" },
    { setup: "What does a pirate say when his wooden leg gets stuck in the freezer?", punchline: "Shiver me timbers!" },
    { setup: "What's a pirate's least favorite vegetable?", punchline: "A leek!" },
    { setup: "How do pirates know they are pirates?", punchline: "They think, therefore they ARRRR!" },
    { setup: "What did the pirate wear on Halloween?", punchline: "A pumpkin patch!" },
    { setup: "Why did the pirate go to the Apple store?", punchline: "He needed a new iPatch!" },
    { setup: "What's a pirate's favorite movie rating?", punchline: "PG-ARRRRR-13!" },
    { setup: "Why couldn't the little kid see the pirate movie?", punchline: "Because it was rated ARRRR!" },
    { setup: "What's a pirate's favorite type of sock?", punchline: "Arrrrgyle!" },
    { setup: "How do you make a pirate furious?", punchline: "Take away the 'P'!" },
    { setup: "What did the pirate say on his 80th birthday?", punchline: "Aye, matey!" },
    { setup: "Why are pirates so good at singing?", punchline: "They can hit the high C's!" },
    { setup: "What does a pirate use to call his mateys?", punchline: "An Aye-Phone!" },
    { setup: "Where do pirates keep their cookies?", punchline: "In a Jarrrrr!" },
    { setup: "What's a pirate's favorite fast food restaurant?", punchline: "Arrrrbys!" },
    { setup: "Why did the pirate break up with his girlfriend?", punchline: "She had a terrible arrrrgument with him." },
    { setup: "What's a pirate's favorite part of a song?", punchline: "The hook!" },
    { setup: "What did the pirate captain say to his new recruit?", punchline: "Welcome aboarrrrd!" },
    { setup: "Why did the pirate bring a ladder to the bar?", punchline: "He heard the drinks were on the house!" },
    { setup: "What do you call a pirate with two eyes and two legs?", punchline: "A beginner." },
    { setup: "What does a pirate put on his toast?", punchline: "Jolly Roger Jellies!" },
    { setup: "Why did the pirate cross the ocean?", punchline: "To get to the other tide!" },
    { setup: "What's a pirate's favorite type of story?", punchline: "A tale of the high C's!" },
    { setup: "What kind of grades did the pirate get in school?", punchline: "High C's!" },
    { setup: "Why was the pirate always looking for his treasure with a computer?", punchline: "He was looking for the X-marks-the-spot.com!" },
    { setup: "What does a pirate wear when it's cold?", punchline: "A long-john silver!" },
    { setup: "How do pirates prefer to communicate?", punchline: "Aye to aye!" },
    { setup: "What happened when Bluebeard fell into the Red Sea?", punchline: "He became Maroonbeard!" },
    { setup: "Why did the teacher wear sunglasses to school?", punchline: "Because her students were so bright!" },
    { setup: "What's a teacher's favorite nation?", punchline: "Expla-nation!" },
    { setup: "Why was the math teacher always so positive?", punchline: "She knew all the angles!" },
    { setup: "What do you call a teacher who doesn’t fart in public?", punchline: "A private tutor!" },
    { setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes!" },
    { setup: "What's a teacher's favorite type of tree?", punchline: "Geome-tree!" },
    { setup: "Why did the teacher bring a ruler to bed?", punchline: "To see how long she slept!" },
    { setup: "What did the student say when the teacher asked for their homework?", punchline: "'My dog ate it... then he asked for seconds!'" },
    { setup: "Why did the teacher jump into the pool?", punchline: "She wanted to test the water!" },
    { setup: "What's a history teacher's favorite fruit?", punchline: "Dates!" },
    { setup: "Why was the English teacher so good at baseball?", punchline: "She knew all the rules of proper nouns and proper slides!" },
    { setup: "What did the pencil say to the teacher?", punchline: "'You always make a good point!'" },
    { setup: "Why did the students like the geography teacher?", punchline: "Because she was down-to-earth!" },
    { setup: "What's a teacher's favorite command on the computer?", punchline: "Ctrl + S (Save the students!)" },
    { setup: "Why did the teacher give the student a C+ in art class?", punchline: "Because they could only draw 'C's and plus signs!" },
    { setup: "What did the science teacher say when her experiment exploded?", punchline: "'Well, that was an uplifting experience!'" },
    { setup: "Why don't teachers ever get lost?", punchline: "They always know the 'class' route!" },
    { setup: "What subject does a witch teacher teach?", punchline: "Spelling!" },
    { setup: "Why was the teacher like a good dictionary?", punchline: "She always had the right words." },
    { setup: "What did the teacher say to the student who was late every day?", punchline: "'You'll be 'tardy' for your own success!'" },
    { setup: "Why did the teacher bring a map to the cafeteria?", punchline: "To find the 'lunch' lines!" },
    { setup: "Why did the teacher write on the window?", punchline: "Because she wanted her lesson to be very clear!" },
    { setup: "What's a teacher's favorite kind of story?", punchline: "One with a good 'class'-ic ending!" },
    { setup: "Why did the teacher always carry a red pen?", punchline: "In case she needed to 'draw blood' from a tough problem!" },
    { setup: "What did the student say to the teacher who was good at gardening?", punchline: "'You really know how to make ideas 'grow'!''" },
    { setup: "Why was the teacher always calm during tests?", punchline: "She had a lot of 'test'-osterone... I mean, patience!" },
    { setup: "What do you call a teacher who loves the beach?", punchline: "Sandy Claus-room!" },
    { setup: "Why did the teacher get an award?", punchline: "For having a lot of 'class'!" },
    { setup: "What does a teacher use to get to school on a snowy day?", punchline: "An 'ice'-icle!" }
];

const catJokes = [
    { setup: "What do you call a cat that's a beauty influencer?", punchline: "A glam-meowr puss." },
    { setup: "Why did the cat bring a ladder to the bar?", punchline: "He heard the drinks were on the house!" },
    { setup: "What's a cat's favorite subject in school?", punchline: "Hiss-tory." },
    { setup: "What do you call a cat who loves to bowl?", punchline: "An alley cat." },
    { setup: "Why are cats so good at video games?", punchline: "Because they have nine lives!" },
    { setup: "What do you get if you cross a cat with a dark horse?", punchline: "Kitty Perry." },
    { setup: "What's a cat's favorite kind of car?", punchline: "A Cat-illac." },
    { setup: "Why was the cat sitting on the computer?", punchline: "To keep an eye on the mouse!" },
    { setup: "What do cats use to make coffee?", punchline: "A purr-colator." },
    { setup: "What do you call a cat that can tell the future?", punchline: "A clairvoy-ant-cat." },
    { setup: "Why did the cat join the Red Cross?", punchline: "She wanted to be a first-aid kit-ten!" },
    { setup: "What is a cat's favorite musical?", punchline: "'Cats'ablanca." },
    { setup: "What do you call a cat who is a police officer?", punchline: "Claw-enforcement." },
    { setup: "Why don't cats play poker in the jungle?", punchline: "Too many cheetahs." },
    { setup: "What's a cat's favorite breakfast?", punchline: "Mice Krispies." },
    { setup: "How do you know if your cat is a good singer?", punchline: "By the meow-sic it makes." },
    { setup: "What do you call a cat that likes to dig in the sand?", punchline: "Sandy Claws." },
    { setup: "What's a cat's favorite button on the remote?", punchline: "Paws." },
    { setup: "Why did the cat go to medical school?", punchline: "To become a purr-amedic." },
    { setup: "What kind of cat works for the C.I.A.?", punchline: "A Siamese-cret agent." },
    { setup: "What do you call a cat that's been caught by the police?", punchline: "A purr-petrator." },
    { setup: "Why did the cat wear a fancy dress to the party?", punchline: "She wanted to look purr-fect." },
    { setup: "What's a cat's favorite ice cream flavor?", punchline: "Mouse-carpone." },
    { setup: "What do you call a cat who is an artist?", punchline: "A paw-casso." },
    { setup: "Why did the cat get a ticket?", punchline: "For littering." },
    { setup: "What's a cat's favorite type of literature?", punchline: "Hairy Paw-ter." },
    { setup: "What do you call it when a cat wins a dog show?", punchline: "A cat-astrophe." },
    { setup: "Why did the cat run away from the tree?", punchline: "It was afraid of the bark." },
    { setup: "What do you call a cat that is very organized?", punchline: "A purr-fectionist." },
    { setup: "What's a cat's favorite game show?", punchline: "The Price is Mice!" },
    { setup: "Why did the cat put oil on the mouse?", punchline: "Because he wanted it to squeak." },
    { setup: "What do you call a lemon-loving cat?", punchline: "A sour puss." },
    { setup: "What's a cat's favorite type of story?", punchline: "A fairy tail." },
    { setup: "Why are cats such good comedians?", punchline: "They always land on their feet with a punchline." },
    { setup: "What do you call a cat that can fix anything?", punchline: "A handyman-cat." },
    { setup: "What's a cat's way of saying 'OMG'?", punchline: "'Oh My Mouse!'" },
    { setup: "Why did the cat go to the library?", punchline: "To check out some mews-papers." },
    { setup: "What's a cat's favorite type of dance?", punchline: "The meow-remba." },
    { setup: "What do you call a cat magician?", punchline: "Meow-dini." },
    { setup: "Why was the cat so good at chess?", punchline: "He was a grand-meow-ster." },
    { setup: "What do you call a cat who loves the snow?", punchline: "A cool cat." },
    { setup: "What's a cat's favorite day of the week?", punchline: "Caturday." },
    { setup: "Why did the cat get an award?", punchline: "For purr-fect attendance." },
    { setup: "What do you call a cat that can play the piano?", punchline: "A meow-sician." },
    { setup: "Why did the cat study law?", punchline: "To become a paw-yer." },
    { setup: "What's a cat's favorite vegetable?", punchline: "As-purr-agus." },
    { setup: "What do you call a cat that's a great detective?", punchline: "Sherlock Paws." },
    { setup: "Why did the cat sit next to the fire?", punchline: "It wanted to be a hot cat." },
    { setup: "What's a cat's favorite dessert?", punchline: "Mice pudding." },
    { setup: "What do you call a cat that tells jokes?", punchline: "A stand-up cat-median." },
    { setup: "Why did the cat join the circus?", punchline: "To be an acro-cat." },
    { setup: "What's a cat's favorite drink?", punchline: "Purr-ier." },
    { setup: "What do you call a cat that loves to read?", punchline: "A literary kit-ten." },
    { setup: "Why did the cat go to space?", punchline: "To visit the meow-ter limits." },
    { setup: "What's a cat's favorite type of movie?", punchline: "A mews-ical." },
    { setup: "What do you call a cat that's a chef?", punchline: "A culinary cat-spert." },
    { setup: "Why did the cat get a promotion?", punchline: "Because of its great cat-titude." },
    { setup: "What's a cat's favorite hobby?", punchline: "Paw-ttery." },
    { setup: "What do you call a cat who is a gardener?", punchline: "A green-pawed feline." },
    { setup: "Why did the cat cross the playground?", punchline: "To get to the other slide... and bat at the swings." },
    { setup: "What's a cat's favorite instrument?", punchline: "The purr-cussion." },
    { setup: "What do you call a group of singing cats?", punchline: "A meow-sical choir." },
    { setup: "Why was the cat so happy?", punchline: "It was feline good." },
    { setup: "What's a cat's favorite thing to wear?", punchline: "A fur coat, naturally!" },
    { setup: "What do you call a cat that's a good leader?", punchline: "The head hon-cat." },
    { setup: "Why did the cat bring string to the party?", punchline: "In case things got tangled." },
    { setup: "What's a cat's favorite superhero?", punchline: "Cat-tain America." },
    { setup: "What do you call a cat who loves to swim?", punchline: "An aqua-cat (though rare!)." },
    { setup: "Why did the cat want to become a weather reporter?", punchline: "To predict purr-cipitation." },
    { setup: "What's a cat's favorite type of tree?", punchline: "A cat-tail tree." },
    { setup: "What do you call a cat that's afraid of everything?", punchline: "A scaredy-cat." },
    { setup: "Why did the cat sit on the dictionary?", punchline: "To learn some new meow-nings." },
    { setup: "What's a cat's favorite board game?", punchline: "Mice and Mystics." },
    { setup: "What do you call a cat who is a champion sleeper?", punchline: "A nap-lete." },
    { setup: "Why did the cat stare at the wall?", punchline: "It was practicing its meow-ditation." },
    { setup: "What's a cat's favorite flower?", punchline: "A tiger lily." },
    { setup: "What do you call a cat that can write?", punchline: "A paw-thor." },
    { setup: "Why did the cat go to the vet?", punchline: "It had a cat-arrh." },
    { setup: "What's a cat's favorite country?", punchline: "Purr-u." },
    { setup: "What do you call a very wealthy cat?", punchline: "A milli-mew-naire." },
    { setup: "Why did the cat start a band?", punchline: "To make some mewsic." },
    { setup: "What's a cat's favorite type of chip?", punchline: "Purr-ingles." },
    { setup: "What do you call a cat that loves to argue?", punchline: "A de-bat-er." },
    { setup: "Why did the cat climb the bookshelf?", punchline: "To get a bird's-eye view... of the mouse." },
    { setup: "What's a cat's favorite city?", punchline: "Paw-ris." },
    { setup: "What do you call a cat who is a spy?", punchline: "A fur-tive agent." },
    { setup: "Why did the cat go to the beach?", punchline: "To catch some rays and some fish!" },
    { setup: "What's a cat's favorite planet?", punchline: "Nep-tune (because it's blue like some cat toys)." },
    { setup: "What do you call a cat that's always on time?", punchline: "Punc-chew-al." },
    { setup: "Why did the cat get a computer?", punchline: "To surf the mouse-wide web." },
    { setup: "What's a cat's favorite TV show?", punchline: "The Great Catsby." },
    { setup: "What do you call a cat that loves to bake?", punchline: "A whisk-er of dough." },
    { setup: "Why did the cat refuse to share its toy?", punchline: "It was being a bit cat-ty." },
    { setup: "What's a cat's favorite kind of story?", punchline: "One with a purr-fect ending." },
    { setup: "What do you call a cat that's good with numbers?", punchline: "A cal-cu-lator." },
    { setup: "Why did the cat sleep under the car?", punchline: "It wanted to wake up oily." },
    { setup: "What's a cat's favorite art movement?", punchline: "Impurr-essionism." },
    { setup: "What do you call a cat that tells secrets?", punchline: "A whisker-blower." },
    { setup: "Why did the cat visit the astrologer?", punchline: "To get its horos-cat read." },
    { setup: "What's a cat's favorite sport?", punchline: "Hairball." },
    { setup: "What do you call a cat that can jump higher than a house?", punchline: "Any cat, houses can't jump!" },
    { setup: "Why did the cat look at the empty food bowl with disdain?", punchline: "It was a cat-titude problem." },
    { setup: "What's a cat's favorite type of party?", punchline: "A fur-ball." },
    { setup: "What do you call a cat that's really good at knitting?", punchline: "A purrl-er." },
    { setup: "Why did the cat become a gardener?", punchline: "It had a green paw." },
    { setup: "What's a cat's favorite holiday?", punchline: "Meow-loween." },
    { setup: "What do you call a pile of cats?", punchline: "A meowtain!" },
    { setup: "Why are cats such bad poker players?", punchline: "They always have a fur ace up their sleeve!" },
    { setup: "What's a cat's favorite color?", punchline: "Purr-ple!" },
    { setup: "What do you call a cat that gets anything it wants?", punchline: "Purr-suasive." },
    { setup: "What's a cat's favorite dessert?", punchline: "Chocolate mouse!" },
    { setup: "What do cats like to eat on a hot day?", punchline: "A mice-cream cone!" },
    { setup: "How do cats end a fight?", punchline: "They hiss and make up!" },
    { setup: "What is a cat's favorite magazine?", punchline: "Good Mousekeeping!" },
    { setup: "Why was the cat so small?", punchline: "Because it only drank condensed milk!" },
    { setup: "What do you call a cat who's a magician?", punchline: "A Meow-gician!" },
    { setup: "What's a cat's favorite song?", punchline: "Three Blind Mice!" },
    { setup: "What state has a lot of cats and dogs?", punchline: "Petsylvania!" },
    { setup: "If lights run on electricity and cars run on gas, what do cats run on?", punchline: "Their paws!" },
    { setup: "What do you call a cat wearing shoes?", punchline: "Puss in Boots!" }
];

const dailyJokes = [
    { setup: "What has keys but opens no locks?", punchline: "A piano." },
    { setup: "What has a neck without a head, a body without legs?", punchline: "A bottle." },
    { setup: "What is full of holes but still holds water?", punchline: "A sponge." },
    { setup: "What question can you never answer yes to?", punchline: "Are you asleep yet?" },
    { setup: "What is always coming but never arrives?", punchline: "Tomorrow." },
    { setup: "What can you break, even if you never pick it up or touch it?", punchline: "A promise." },
    { setup: "What goes up but never comes down?", punchline: "Your age." },
    { setup: "What has a thumb and four fingers but is not alive?", punchline: "A glove." },
    { setup: "What has one voice, but speaks in every language?", punchline: "An echo." },
    { setup: "What has cities, but no houses; forests, but no trees; and water, but no fish?", punchline: "A map." },
    { setup: "Why did the student bring a ladder to school?", punchline: "To go to high school!" },
    { setup: "What do you call a dinosaur that is sleeping?", punchline: "A dino-snore." },
    { setup: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
    { setup: "Why did the teddy bear say no to dessert?", punchline: "Because she was stuffed." },
    { setup: "What gets wetter the more it dries?", punchline: "A towel." },
    { setup: "Why did an orange stop running in the race?", punchline: "Because it ran out of juice!" },
    { setup: "What animal can jump higher than a house?", punchline: "All of them, houses can't jump!" },
    { setup: "Why was the math book unhappy?", punchline: "Because it had too many problems." },
    { setup: "What is a pirate's favorite letter of the alphabet?", punchline: "You might think it's R, but their first love is the C!" },
    { setup: "What do you call a lazy kangaroo?", punchline: "Pouch potato." },
    { setup: "Why did the bicycle fall over?", punchline: "Because it was two-tired." },
    { setup: "What time is it when an elephant sits on a fence?", punchline: "Time to fix the fence!" },
    { setup: "What do you call a boomerang that doesn’t come back?", punchline: "A stick." },
    { setup: "Why did the cookie go to the doctor?", punchline: "Because it felt crummy." },
    { setup: "What do you call a cheese that isn't yours?", punchline: "Nacho cheese!" },
    { setup: "What kind of tree fits in your hand?", punchline: "A palm tree." },
    { setup: "How do you make a milkshake?", punchline: "Give a cow a pogo stick." },
    { setup: "Why can't you give Elsa a balloon?", punchline: "Because she will let it go." },
    { setup: "What do you call a snowman party?", punchline: "A snowball." },
    { setup: "What has an end, but no beginning?", punchline: "A rainbow." },
    { setup: "What do you call a dog magician?", punchline: "A labracadabrador." },
    { setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },
    { setup: "What do you call fake spaghetti?", punchline: "An impasta." },
    { setup: "What is brown and sticky?", punchline: "A stick." },
    { setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts." },
    { setup: "What concert costs just 45 cents?", punchline: "50 Cent featuring Nickelback." },
    { setup: "What did the ocean say to the beach?", punchline: "Nothing, it just waved." },
    { setup: "What is easy to get into, but hard to get out of?", punchline: "Trouble." },
    { setup: "Why did the scientist install a knocker on his door?", punchline: "He wanted to win the No-bell prize!" },
    { setup: "What do you call a fly without wings?", punchline: "A walk." },
    { setup: "What do you call a belt made out of watches?", punchline: "A waist of time." },
    { setup: "Why are ghosts such bad liars?", punchline: "Because you can see right through them." },
    { setup: "What goes up and down but doesn’t move?", punchline: "A staircase." },
    { setup: "What can you catch, but not throw?", punchline: "A cold." },
    { setup: "What has words, but never speaks?", punchline: "A book." },
    { setup: "Why did the girl throw butter out the window?", punchline: "She wanted to see a butterfly." },
    { setup: "What is a vampire's favorite fruit?", punchline: "A neck-tarine." },
    { setup: "What do you call a fish with no eyes?", punchline: "Fsh!" },
    { setup: "Why did the tomato turn red?", punchline: "Because it saw the salad dressing." },
    { setup: "What do you call a sleeping piece of paper?", punchline: "A nap-kin." },
    { setup: "How do you organize a space party?", punchline: "You planet." },
    { setup: "What kind of key opens a banana?", punchline: "A monkey." },
    { setup: "What do you call a bear that's stuck in the rain?", punchline: "A drizzly bear." },
    { setup: "Why was the computer cold?", punchline: "It left its Windows open." },
    { setup: "What do you call a line of rabbits hopping backwards?", punchline: "A receding hare-line." },
    { setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
    { setup: "What do you call an alligator in a vest?", punchline: "An investigator." },
    { setup: "Why did the student sit on his watch?", punchline: "He wanted to be on time." },
    { setup: "What do you call a group of musical whales?", punchline: "An orca-stra." },
    { setup: "What kind of music do planets like?", punchline: "Nep-tunes." },
    { setup: "Why did the boy bring a flashlight to school?", punchline: "His teacher told him it was a bright class." },
    { setup: "What do you call a cheese that likes to shoot hoops?", punchline: "Swish cheese." },
    { setup: "Why was the broom late for school?", punchline: "It over-swept." },
    { setup: "What has a face and two hands but no arms or legs?", punchline: "A clock." },
    { setup: "What do you call a number that just can't stand still?", punchline: "A roamin' numeral." },
    { setup: "Why did the kid cross the playground?", punchline: "To get to the other slide." },
    { setup: "What is black and white and read all over?", punchline: "A newspaper." },
    { setup: "Why did the chewing gum cross the road?", punchline: "It was stuck to the chicken's foot." },
    { setup: "What do you call a dinosaur with a good vocabulary?", punchline: "A thesaurus." },
    { setup: "Why did the soccer ball quit the team?", punchline: "It was tired of being kicked around." },
    { setup: "What do you call a pig that knows karate?", punchline: "A pork chop." },
    { setup: "What is a ninja's favorite type of shoes?", punchline: "Sneakers." },
    { setup: "Why did the golfer wear two pairs of pants?", punchline: "In case he got a hole in one." },
    { setup: "What do you call a sad coffee?", punchline: "Depresso." },
    { setup: "Why did the skeleton go to the party alone?", punchline: "He had no body to go with." },
    { setup: "What can travel around the world while staying in a corner?", punchline: "A stamp." },
    { setup: "What fruit is a vampire's favorite?", punchline: "A blood orange." },
    { setup: "What do you call a thieving monkey?", punchline: "A prime-ape." },
    { setup: "Why did the artist break up with the mathematician?", punchline: "They had too many differences." },
    { setup: "What do you call a teacher who doesn’t fart in public?", punchline: "A private tutor." },
    { setup: "Why was the stadium so cool?", punchline: "It was full of fans." },
    { setup: "What do you call a magical dog?", punchline: "A Labracadabrador." },
    { setup: "Why are fish so smart?", punchline: "They live in schools." },
    { setup: "What is a pirate's favorite exercise?", punchline: "The plank!" },
    { setup: "Why did the calendar factory hire a new person?", punchline: "They needed someone to take more days off." },
    { setup: "What do you call a factory that sells good products?", punchline: "A satisfactory." },
    { setup: "What do you call an old snowman?", punchline: "Water." },
    { setup: "What is always in front of you but can’t be seen?", punchline: "The future." },
    { setup: "What starts with a P, ends with an E, and has thousands of letters?", punchline: "The Post Office." },
    { setup: "Why did the phone wear glasses?", punchline: "It lost its contacts." },
    { setup: "What do you call a camel with no humps?", punchline: "Humphrey." },
    { setup: "Why did the student bring a pencil to bed?", punchline: "To draw the curtains!" },
    { setup: "What did the traffic light say to the car?", punchline: "Don't look! I'm about to change." },
    { setup: "What do you call a cow with two legs?", punchline: "Lean beef." },
    { setup: "What do you call a cow with no legs?", punchline: "Ground beef." },
    { setup: "Why did the library books get scared?", punchline: "They heard the librarian was checking them out." },
    { setup: "What do you call a funny mountain?", punchline: "Hill-arious." },
    { setup: "Why did the banana go to the doctor?", punchline: "Because it wasn't peeling well." },
    { setup: "What do you call a robot that takes the scenic route?", punchline: "R2-Detour." },
    { setup: "Why did the baker stop making bread?", punchline: "He kneaded a break." },
    { setup: "What do you call a dog that can tell time?", punchline: "A watchdog." },
    { setup: "What do you call a pile of cats?", punchline: "A meowtain." },
    { setup: "Why did the students like their math teacher?", punchline: "Because he was always fair and square." },
    { setup: "What do you call a person who is afraid of Santa Claus?", punchline: "Claustrophobic." },
    { setup: "What do you call a fish with a tie?", punchline: "So-fish-ticated." },
    { setup: "What has an eye, but cannot see?", punchline: "A needle." },
    { setup: "What has to be broken before you can use it?", punchline: "An egg." },
    { setup: "What has one head, one foot, and four legs?", punchline: "A bed." },
    { setup: "Why did the student eat his homework?", punchline: "Because the teacher said it was a piece of cake!" },
    { setup: "What building has the most stories?", punchline: "The library." },
    { setup: "What musical instrument is found in the bathroom?", punchline: "A tuba toothpaste." },
    { setup: "Why was the equal sign so humble?", punchline: "Because he knew he wasn’t less than or greater than anyone else." },
    { setup: "What do you call a sad strawberry?", punchline: "A blueberry." },
    { setup: "What is a witch's favorite subject in school?", punchline: "Spelling!" },
    { setup: "What do you get when you cross a snowman and a vampire?", punchline: "Frostbite." },
    { setup: "Why did the orange stop running?", punchline: "It ran out of juice!" },
    { setup: "How do you make a tissue dance?", punchline: "You put a little boogie in it!" },
    { setup: "What do you call a sleeping bull?", punchline: "A bulldozer!" },
    { setup: "What is a pirate's favorite letter?", punchline: "RRRR? You'd think so, but their first love is the C!" },
    { setup: "Why did Dad bring a ladder to the grocery store?", punchline: "He heard the prices were high!" },
    { setup: "What did Mom say when she fixed the broken toy?", punchline: "'I'm not a magician, but I have my 'mom'-ents!'" },
    { setup: "Why is Dad like a human GPS?", punchline: "He always thinks he knows the best route, even when he doesn't!" },
    { setup: "What's a mom's favorite saying when you can't find something?", punchline: "'It's in the last place you'd look!' (Because then you stop looking!)" },
    { setup: "Why did Dad tiptoe past the medicine cabinet?", punchline: "He didn't want to wake up the sleeping pills!" },
    { setup: "What's the difference between a dad joke and a bad joke?", punchline: "The first letter!" },
    { setup: "Why did Mom put the family photos in the blender?", punchline: "She wanted to make a family shake!" },
    { setup: "How do you know if your dad is telling a joke?", punchline: "He says, 'This one will crack you up!'... and then it doesn't." },
    { setup: "What's a mom's superpower?", punchline: "Finding lost things with her eyes closed!" },
    { setup: "Why did Dad start a band with the vegetables?", punchline: "He wanted to play some 'beet' music!" },
    { setup: "Why did Dad sit on the remote control?", punchline: "He wanted to be in charge of the channels!" },
    { setup: "What's Mom's favorite kind of music to clean to?", punchline: "Something with a good 'sweep' beat!" },
    { setup: "Why did Dad wear two pairs of socks while golfing?", punchline: "In case he got a hole-in-one... in his sock!" },
    { setup: "What's a mom's secret ingredient for making everything better?", punchline: "A little bit of 'mom'-gic!" },
    { setup: "Why did Dad bring a flashlight to the dinner table?", punchline: "He heard it was going to be a 'light' meal!" },
    { setup: "Why did the older sibling give the younger sibling a map?", punchline: "To help them find their way... to their own room!" },
    { setup: "What do you call a brother who is always on the computer?", punchline: "A screen-ager!" },
    { setup: "Why are little brothers and sisters like alarms?", punchline: "They always go off when you least expect it!" },
    { setup: "What did one sibling say to the other after an argument?", punchline: "'You're annoying, but you're my kind of annoying!'" },
    { setup: "Why is it hard to keep a secret from your sister?", punchline: "Because what's 'hers' is 'hers', and what's 'yours' is also 'hers' to know!" },
    { setup: "What's the best thing about having an older brother?", punchline: "Someone to blame things on! (Just kidding... mostly!)" },
    { setup: "Why did the siblings bring a ladder to the park?", punchline: "To take their arguments to a higher level!" },
    { setup: "How do you stop your little sister from reading your diary?", punchline: "You write it in code that only you and your pet rock understand." },
    { setup: "What's a sibling's favorite game?", punchline: "'Who can annoy the other one first?'" },
    { setup: "Why are siblings like a good Wi-Fi signal?", punchline: "Sometimes strong, sometimes weak, but you can't live without them!" },
    { setup: "What's the hardest part about sharing a room with your sibling?", punchline: "Sharing the air!" },
    { setup: "Why did the older sister hide the younger brother's favorite toy?", punchline: "She said it was for 'safekeeping'... from him!" },
    { setup: "What do you call it when your brother eats the last cookie?", punchline: "A 'crumby' situation!" },
    { setup: "Why are siblings like built-in best friends and rivals?", punchline: "Because they know all your best moves... and all your secret snacks!" },
    { setup: "Why are grandparents the best storytellers?", punchline: "Because they have 'grand' imaginations!" },
    { setup: "What do you call a grandpa who tells amazing jokes?", punchline: "A 'pun'-pa!" },
    { setup: "Why did Grandma knit sweaters for the vegetables?", punchline: "She wanted them to have a 'cozy' winter!" },
    { setup: "What's an aunt's favorite type of music?", punchline: "Anything that makes her 'aunt-icipate' dancing!" },
    { setup: "Why did Grandpa bring a net to the family dinner?", punchline: "He heard there were going to be 'fish' stories!" },
    { setup: "What do you call a cool uncle?", punchline: "An 'ice' uncle!" },
    { setup: "Why are grandmas so good at baking cookies?", punchline: "They have a 'batch' of experience!" },
    { setup: "What did the cousin say when they couldn't find their shoes?", punchline: "'This is a 'sole'-crushing experience!'" },
    { setup: "Why do grandparents give the best hugs?", punchline: "Because they're full of 'grand'-ness and love!" },
    { setup: "What's a grandpa's favorite remote control button?", punchline: "The 'snooze' button... for his afternoon nap!" },
    { setup: "Why was the family picture always a little blurry?", punchline: "Because someone always 'moved' by the family drama!" },
    { setup: "What do you call a family of musical fruit?", punchline: "A jam session!" },
    { setup: "Why did the family bring a ladder to the picnic?", punchline: "To reach the high expectations for fun!" },
    { setup: "What's a family's favorite board game?", punchline: "Life... because it's always an adventure!" }
];

const spanishJokes = [
    {
        setup: "¿Qué le dice un jaguar a otro jaguar?",
        setup_en: "What does one jaguar say to another jaguar?",
        punchline: "¡Jaguar you!",
        punchline_en: "(Sounds like 'How are you!')"
    },
    {
        setup: "Why was the math book sad in Spanish class?",
        setup_en: "(Same as setup)",
        punchline: "Porque tenía demasiados problemas.",
        punchline_en: "Because it had too many problems."
    },
    {
        setup: "¿Cómo se llama un boomerang que no vuelve?",
        setup_en: "What do you call a boomerang that doesn't come back?",
        punchline: "Un palo.",
        punchline_en: "A stick."
    },
    {
        setup: "What do you call a tired dog in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Un Cansado.",
        punchline_en: "(Cansado = tired; 'can' is a root for dog, like 'canine')"
    },
    {
        setup: "¿Cuál es el animal que es dos veces animal?",
        setup_en: "Which animal is an animal twice?",
        punchline: "El gato, porque es gato y araña.",
        punchline_en: "The cat, because it's a cat (gato) and it scratches (araña also means 'scratches', or spider)."
    },
    {
        setup: "What does a Spanish cow say?",
        setup_en: "(Same as setup)",
        punchline: "Múúúúú!",
        punchline_en: "(Moo!)"
    },
    {
        setup: "¿Qué hace una abeja en el gimnasio?",
        setup_en: "What does a bee do in the gym?",
        punchline: "¡Zum-ba!",
        punchline_en: "(Zumba! - 'zum' is like buzz)"
    },
    {
        setup: "Why did the tortilla chip start dancing?",
        setup_en: "(Same as setup)",
        punchline: "Because they put on the salsa!",
        punchline_en: "(Salsa music / salsa dip)"
    },
    {
        setup: "¿Qué dice el semáforo al coche?",
        setup_en: "What does the traffic light say to the car?",
        punchline: "'No me mires, ¡me estoy cambiando!'",
        punchline_en: "'Don't look at me, I'm changing!'"
    },
    {
        setup: "What is a Spanish vampire's favorite fruit?",
        setup_en: "(Same as setup)",
        punchline: "Naranja sangre.",
        punchline_en: "Blood orange."
    },
    {
        setup: "¿Por qué fue la niña al doctor con un lápiz en la oreja?",
        setup_en: "Why did the girl go to the doctor with a pencil in her ear?",
        punchline: "Porque quería tener 'dibujo de oído'.",
        punchline_en: "Because she wanted 'ear drawing' (a pun on 'buen oído' meaning good hearing)."
    },
    {
        setup: "¿Qué le dijo un techo a otro techo?",
        setup_en: "What did one roof say to another roof?",
        punchline: "Techo de menos.",
        punchline_en: "(Sounds like 'te echo de menos' - I miss you.)"
    },
    {
        setup: "What do you call cheese that isn't yours in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Queso ajeno. (But the classic is Nacho Cheese!)",
        punchline_en: "Someone else's cheese. (But the classic is Nacho Cheese!)"
    },
    {
        setup: "If you're sad and you speak Spanish, are you de-stressed or 'depressed' in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Deprimido.",
        punchline_en: "(Depressed.)"
    },
    {
        setup: "Why did the student bring a ladder to Spanish class?",
        setup_en: "(Same as setup)",
        punchline: "To reach 'altas notas'!",
        punchline_en: "(To reach high grades / high notes!)"
    },
    {
        setup: "¿Cuál es el café más peligroso del mundo?",
        setup_en: "What is the most dangerous coffee in the world?",
        punchline: "El ex-preso.",
        punchline_en: "The ex-prisoner (ex-preso) / Espresso (expreso)."
    },
    {
        setup: "What do you call a sleeping pizza in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "A pizzzzza.",
        punchline_en: "(Same punchline, emphasizing the 'zzzz' for sleep)"
    },
    {
        setup: "¿Qué le dice un espagueti a otro?",
        setup_en: "What does one spaghetti say to another?",
        punchline: "¡Oye, mi cuerpo me pide salsa!",
        punchline_en: "Hey, my body is asking for salsa/sauce!"
    },
    {
        setup: "Why did the tomato turn red when it saw the salad?",
        setup_en: "(Same as setup)",
        punchline: "Porque vio el aderezo.",
        punchline_en: "Because it saw the salad dressing!"
    },
    {
        setup: "¿Cómo se dice 'dentist' en japonés?",
        setup_en: "How do you say 'dentist' in Japanese?",
        punchline: "Tekito Tuka.",
        punchline_en: "(Sounds like 'te quito tu caries' - I remove your cavity)"
    },
    {
        setup: "What does a nosey pepper do?",
        setup_en: "(Same as setup)",
        punchline: "Se mete en jalapeños asuntos.",
        punchline_en: "Gets into jalapeño business (gets into other people's business)."
    },
    {
        setup: "¿Por qué los pájaros pequeños vuelan juntos?",
        setup_en: "Why do little birds fly together?",
        punchline: "¡Para ser pío-nieros!",
        punchline_en: "To be pio-neers! ('Pío' is the sound 'chirp', like pioneers)"
    },
    {
        setup: "What's a ghost's favorite dessert in Mexico?",
        setup_en: "(Same as setup)",
        punchline: "Boo-ñuelos!",
        punchline_en: "(Buñuelos are a type of fritter; 'Boo' like a ghost sound)"
    },
    {
        setup: "¿Qué le dijo una iguana a su hermana gemela?",
        setup_en: "What did one iguana say to her twin sister?",
        punchline: "Somos iguanitas.",
        punchline_en: "We are little iguanas (iguanitas) / We are identical (igualitas - sounds similar)."
    },
    {
        setup: "Why don't fish play basketball in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Porque tienen miedo a la red.",
        punchline_en: "Because they are afraid of the net (basketball net / fishing net)."
    },
    {
        setup: "¿Cuál es el último animal que subió al arca de Noé?",
        setup_en: "What was the last animal to get on Noah's ark?",
        punchline: "El del-fín.",
        punchline_en: "The dolphin (delfín) / The end (el fin)."
    },
    {
        setup: "What do you call a bear with no teeth in Spanish class?",
        setup_en: "(Same as setup)",
        punchline: "Un oso gomoso.",
        punchline_en: "A gummy bear."
    },
    {
        setup: "¿Cómo estornuda un tomate?",
        setup_en: "How does a tomato sneeze?",
        punchline: "¡Catsup!",
        punchline_en: "(Ketchup!)"
    },
    {
        setup: "What did the number zero say to the number eight?",
        setup_en: "(Same as setup)",
        punchline: "¡Qué bonito cinturón!",
        punchline_en: "Nice belt!"
    },
    {
        setup: "¿Qué hace un perro con un taladro?",
        setup_en: "What does a dog do with a drill?",
        punchline: "Ta-ladrando.",
        punchline_en: "It's drilling (taladrando) / It's barking (ladrando)."
    },
    {
        setup: "Why was the Spanish book always calm?",
        setup_en: "(Same as setup)",
        punchline: "Porque tenía mucha pa-ciencia.",
        punchline_en: "Because it had a lot of patience (paciencia) / pa-science ('ciencia' is science)."
    },
    {
        setup: "¿Cuál es la fruta más divertida?",
        setup_en: "What is the most fun fruit?",
        punchline: "La naranja ja-ja.",
        punchline_en: "The orange ha-ha (naranja)."
    },
    {
        setup: "What is a vampire's favorite type of ship in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Un buque de sangre.",
        punchline_en: "A blood vessel / A ship of blood."
    },
    {
        setup: "¿Qué le dice un gusano a otro gusano?",
        setup_en: "What does one worm say to another worm?",
        punchline: "Voy a dar una vuelta a la manzana.",
        punchline_en: "I'm going for a walk around the block / around the apple."
    },
    {
        setup: "Why did the student study in an airplane in Spain?",
        setup_en: "(Same as setup)",
        punchline: "Quería obtener un título de alto vuelo.",
        punchline_en: "He wanted to get a high-flying degree."
    },
    {
        setup: "¿Qué le dice una pared a otra pared?",
        setup_en: "What does one wall say to another wall?",
        punchline: "Nos vemos en la esquina.",
        punchline_en: "See you at the corner."
    },
    {
        setup: "What do you call a fish that wears a crown in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Un rey pez.",
        punchline_en: "A kingfish."
    },
    {
        setup: "¿Por qué el libro de matemáticas está siempre preocupado?",
        setup_en: "Why is the math book always worried?",
        punchline: "Porque tiene muchos problemas.",
        punchline_en: "Because it has many problems."
    },
    {
        setup: "What did one hat say to the other hat in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Quédate aquí, yo voy a dar una vuelta a la cabeza.",
        punchline_en: "Stay here, I'm going for a spin around the head."
    },
    {
        setup: "¿Cómo se llama el campeón de buceo japonés?",
        setup_en: "What is the name of the Japanese diving champion?",
        punchline: "Tokofondo.",
        punchline_en: "(Sounds like 'toco fondo' - I hit the bottom.)"
    },
    {
        setup: "Why did the students like the Spanish dictionary?",
        setup_en: "(Same as setup)",
        punchline: "Porque siempre tenía la palabra correcta.",
        punchline_en: "Because it always had the right word."
    },
    {
        setup: "¿Qué le dice una uva verde a una uva morada?",
        setup_en: "What does a green grape say to a purple grape?",
        punchline: "¡Respira!",
        punchline_en: "Breathe!"
    },
    {
        setup: "What's a cat's favorite button on a Spanish remote control?",
        setup_en: "(Same as setup)",
        punchline: "Pawsar.",
        punchline_en: "(Sounds like 'pausar' - to pause.)"
    },
    {
        setup: "¿Por qué el mar no se seca?",
        setup_en: "Why doesn't the sea dry up?",
        punchline: "Porque no tiene toalla.",
        punchline_en: "Because it doesn't have a towel."
    },
    {
        setup: "Why did the computer go to the doctor in Mexico City?",
        setup_en: "(Same as setup)",
        punchline: "Porque tenía un virus y necesitaba un anti-virus con chile.",
        punchline_en: "Because it had a virus and needed an anti-virus with chili."
    },
    {
        setup: "¿Cuál es el baile favorito del tomate?",
        setup_en: "What is the tomato's favorite dance?",
        punchline: "La salsa.",
        punchline_en: "Salsa."
    },
    {
        setup: "What's a Mexican magician's favorite phrase?",
        setup_en: "(Same as setup)",
        punchline: "¡Nada por aquí, nada por allá, y ahora unos tacos!",
        punchline_en: "Nothing here, nothing there, and now some tacos!"
    },
    {
        setup: "¿Por qué los esqueletos no pelean en España?",
        setup_en: "Why don't skeletons fight in Spain?",
        punchline: "Porque no tienen agallas.",
        punchline_en: "Because they don't have guts."
    },
    {
        setup: "What do you call a sad strawberry in Spanish class?",
        setup_en: "(Same as setup)",
        punchline: "Una fresa deprimida.",
        punchline_en: "A depressed strawberry."
    },
    {
        setup: "¿Cómo se despiden los químicos?",
        setup_en: "How do chemists say goodbye?",
        punchline: "Ácido un placer.",
        punchline_en: "It's been a pleasure (ha sido un placer) / Acid a pleasure (Ácido un placer)."
    },
    {
        setup: "Why did the student eat his Spanish homework?",
        setup_en: "(Same as setup)",
        punchline: "Porque la maestra dijo que era pan comido.",
        punchline_en: "Because the teacher said it was a piece of cake (pan comido - literally 'eaten bread')."
    },
    {
        setup: "¿Cuál es el animal más antiguo?",
        setup_en: "What is the oldest animal?",
        punchline: "La cebra, porque está en blanco y negro.",
        punchline_en: "The zebra, because it's in black and white."
    },
    {
        setup: "What do you call a lazy joey in Spanish?",
        setup_en: "(Same as setup)",
        punchline: "Un cangurito perezoso.",
        punchline_en: "A lazy little kangaroo."
    },
    {
        setup: "¿Qué le dijo el número 1 al número 10?",
        setup_en: "What did the number 1 say to the number 10?",
        punchline: "Para ser como yo, tienes que ser sincero.",
        punchline_en: "To be like me, you have to be sincere (sincero) / without zero (sin cero)."
    },
    {
        setup: "Why did the bicycle fall over in Spain?",
        setup_en: "(Same as setup)",
        punchline: "Porque estaba dos-cansada.",
        punchline_en: "Because it was two-tired (dos - two) / too tired (cansada - tired)."
    },
    {
        setup: "¿Qué hace una vaca pensando?",
        setup_en: "What is a thinking cow doing?",
        punchline: "Leche concentrada.",
        punchline_en: "Concentrated milk."
    },
    {
        setup: "What do you call a group of musical whales near Spain?",
        setup_en: "(Same as setup)",
        punchline: "Una orca-esta.",
        punchline_en: "(An orchestra - orquesta)"
    },
    {
        setup: "¿Por qué los diabéticos no pueden vengarse?",
        setup_en: "Why can't diabetics take revenge?",
        punchline: "Porque la venganza es dulce.",
        punchline_en: "Because revenge is sweet."
    },
    {
        setup: "What’s a baker’s favorite Spanish greeting?",
        setup_en: "(Same as setup)",
        punchline: "¡Hola Pan!",
        punchline_en: "Hello Bread! (Pan - bread)"
    },
    {
        setup: "¿Qué le dice un semáforo a un conductor enojado?",
        setup_en: "What does a traffic light say to an angry driver?",
        punchline: "¡No me cambies el color!",
        punchline_en: "Don't change my color! / Don't change my mood!"
    },
    {
        setup: "Why are Spanish skeletons so calm?",
        setup_en: "(Same as setup)",
        punchline: "Porque nada les llega al hueso.",
        punchline_en: "Because nothing gets to their bones (under their skin)."
    },
    {
        setup: "¿Qué es amarillo por fuera y plátano por dentro?",
        setup_en: "What is yellow on the outside and banana on the inside?",
        punchline: "¡Un plátano!",
        punchline_en: "A banana!"
    },
    {
        setup: "What's a Spanish sheep's favorite music?",
        setup_en: "(Same as setup)",
        punchline: "Baa-chata.",
        punchline_en: "(Bachata - a type of music)"
    },
    {
        setup: "¿Cuál es el colmo de un jardinero?",
        setup_en: "What is the ultimate misfortune for a gardener?",
        punchline: "Que su novia se llame Rosa y lo deje plantado.",
        punchline_en: "That his girlfriend's name is Rose (Rosa) and she stands him up (leaves him planted - plantado)."
    },
    {
        setup: "What is a Spanish owl's favorite subject?",
        setup_en: "(Same as setup)",
        punchline: "Owl-gebra.",
        punchline_en: "(Algebra)"
    },
    {
        setup: "¿Qué le dice un fideo a otro en la sopa?",
        setup_en: "What does one noodle say to another in the soup?",
        punchline: "¡Qué ambiente más caldoso!",
        punchline_en: "What a brothy (caldoso) atmosphere!"
    },
    {
        setup: "Why was the little Spanish book always happy?",
        setup_en: "(Same as setup)",
        punchline: "Porque tenía un buen final.",
        punchline_en: "Because it had a good ending."
    },
    {
        setup: "What sound does a Spanish ambulance make?",
        setup_en: "(Same as setup)",
        punchline: "Nino-nino-nino... ¡ayuda!",
        punchline_en: "(Nee-naw sound... help!)"
    },
    {
        setup: "¿Cómo se dice 'naufrago' en chino?",
        setup_en: "How do you say 'shipwrecked person' in Chinese?",
        punchline: "Chin chu lan cha.",
        punchline_en: "(Sounds like 'sin su lancha' - without his boat.)"
    },
    {
        setup: "Why did the math student bring a map to class in Madrid?",
        setup_en: "(Same as setup)",
        punchline: "Para encontrar la X.",
        punchline_en: "To find X."
    },
    {
        setup: "¿Qué le dijo una pulga a otra pulga?",
        setup_en: "What did one flea say to another flea?",
        punchline: "¿Vamos a pie o esperamos al perro?",
        punchline_en: "Shall we go on foot or wait for the dog?"
    },
    {
        setup: "What do you call a Spanish dog that does magic?",
        setup_en: "(Same as setup)",
        punchline: "Un perro-cadabra.",
        punchline_en: "(A dog-cadabra)"
    },
    {
        setup: "¿Cuál es el animal que siempre llega tarde?",
        setup_en: "Which animal always arrives late?",
        punchline: "El caracol.",
        punchline_en: "The snail."
    },
    {
        setup: "Why are Spanish jokes so cool?",
        setup_en: "(Same as setup)",
        punchline: "Porque son muy fresco.",
        punchline_en: "Because they are very fresh/cool."
    },
    {
        setup: "¿Cómo se dice pañuelo en japonés?",
        setup_en: "How do you say 'handkerchief' in Japanese?",
        punchline: "Saka Moko.",
        punchline_en: "(Sounds like 'saca moco' - takes out booger.)"
    },
    {
        setup: "What does a Spanish lightbulb say when it has an idea?",
        setup_en: "(Same as setup)",
        punchline: "¡Tengo una idea brillante!",
        punchline_en: "I have a brilliant idea!"
    },
    {
        setup: "¿Qué hace una abeja en el gimnasio gritando?",
        setup_en: "What does a bee do in the gym yelling?",
        punchline: "¡Zum-BAILA!",
        punchline_en: "(Zumba-DANCE! - 'baila' means dance)"
    },
    {
        setup: "Why did the Spanish student bring a fork to math class?",
        setup_en: "(Same as setup)",
        punchline: "Porque iba a haber división.",
        punchline_en: "Because there was going to be division."
    },
    {
        setup: "What's a Mexican cow's favorite holiday?",
        setup_en: "(Same as setup)",
        punchline: "Moo-chos Gracias Day!",
        punchline_en: "(Muchos Gracias - Thank you very much / Thanksgiving)"
    }
];

const schoolJokes = [
    { setup: "Why did Coco the Mountain Lion bring a ladder to World Compass Academy?", punchline: "He heard the grades were high!" },
    { setup: "What's Coco's favorite subject at World Compass Academy?", punchline: "ROAR-t class!" },
    { setup: "Why is World Compass Academy like a good map?", punchline: "It always points you in the right direction!" },
    { setup: "What do World Compass Academy students and Castle Rock have in common?", punchline: "They both ROCK!" },
    { setup: "Why did Coco get a job at World Compass Academy?", punchline: "He wanted to be the 'mane' attraction!" },
    { setup: "What's Coco the Mountain Lion's favorite game at recess?", punchline: "Tag, you're it... I'm faster!" },
    { setup: "How does Coco help World Compass Academy students navigate their studies?", punchline: "With his excellent 'compass' sense!" },
    { setup: "Why are World Compass Academy students so smart?", punchline: "They're always 'exploring' new ideas!" },
    { setup: "What does Coco say when he learns something new?", punchline: "That's purr-fectly interesting!" },
    { setup: "Why did the student bring a compass to lunch at World Compass Academy?", punchline: "To find the 'point' of the sandwich!" },
    { setup: "What's Coco's favorite part of Castle Rock?", punchline: "The 'castle' part, of course!" },
    { setup: "What do you call Coco when he's solving a puzzle?", punchline: "A 'think-lion' outside the box!" },
    { setup: "Why is World Compass Academy the best school?", punchline: "Because it helps you find your 'true north'!" },
    { setup: "What kind of stories does Coco like?", punchline: "Ones with a good 'tail'!" },
    { setup: "Why was Coco so good at hide-and-seek in Castle Rock?", punchline: "He's a master of 'cam-eow-flage' among the rocks!" },
    { setup: "What are Coco the Cougar's favorite colors at World Compass Academy?", punchline: "Blue, green, and purr-white!" },
    { setup: "Why do World Compass Academy students always look so sharp in their uniforms?", punchline: "Because they're dressed for success, Cougar style!" },
    { setup: "What did the green uniform say to the blue uniform at World Compass Academy?", punchline: "'You make me feel a little blue, but together we're a great team!'" },
    { setup: "Why are there so many paw prints at World Compass Academy?", punchline: "Because Coco the Cougar is always prowling for knowledge!" },
    { setup: "What's Coco's favorite thing about the World Compass Academy uniforms?", punchline: "They all look purr-fessionally smart!" },
    { setup: "If World Compass Academy had a garden, what would it grow?", punchline: "Blue-berries, green beans, and white-lilies, of course!" },
    { setup: "Why did the World Compass Academy student bring a blue marker, a green crayon, and white paper to art class?", punchline: "To paint a purr-fect school spirit picture!" },
    { setup: "What do you call a very tidy Cougar at World Compass Academy?", punchline: "A neat freak with clean paw prints!" },
    { setup: "Why did Coco the Cougar wear his blue, green, and white scarf?", punchline: "To show his World Compass Academy pride, even on a chilly day!" },
    { setup: "How do World Compass Academy students follow directions so well?", punchline: "They follow the Cougar paw prints to success!" },
    { setup: "What's a World Compass Academy student's favorite type of music?", punchline: "Anything with a good 'blue-green' beat!" },
    { setup: "Why are the walls at World Compass Academy so inspiring?", punchline: "Because they're covered in wise words and Cougar paw-sitivity!" },
    { setup: "What did the white stripe on the uniform say to the green stripe?", punchline: "'With blue, we make World Compass Academy look serene!'" },
    { setup: "How does Coco the Cougar keep his uniform so clean?", punchline: "With extra 'fur-breeze' and careful paw-lacement!" },
    { setup: "Why did the World Compass Academy student excel in geography?", punchline: "Because they knew how to navigate the 'World' with their 'Compass'!" },
    { setup: "What's Coco's favorite type of math at World Compass Academy?", punchline: "Geome-tree, especially the blue spruce and green pines!" },
    { setup: "Why do World Compass Academy students make great detectives?", punchline: "They always follow the paw prints to find the clues!" },
    { setup: "What's the most stylish accessory for a World Compass Academy uniform?", punchline: "A big Cougar smile and a touch of blue, green, or white!" },
    { setup: "Why was Coco the Cougar so good at the World Compass Academy spelling bee?", punchline: "He knew all the 'impaw-tant' words!" },
    { setup: "What do you get if you mix World Compass Academy's blue and green?", punchline: "A very happy Cougar in a beautiful teal landscape!" },
    { setup: "Why did the new student at World Compass Academy feel right at home?", punchline: "Because everyone was so 'paw-some' and welcoming!" },
    { setup: "What's Coco's favorite part of the World Compass Academy playground?", punchline: "The parts painted blue, green, and white, where he leaves his paw prints!" },
    { setup: "How do you know a World Compass Academy student is nearby?", punchline: "You'll see their smart uniform and a trail of good deeds (and maybe tiny paw prints)!" },
    { setup: "Why is the World Compass Academy library so quiet?", punchline: "Because Coco is there, 'purr-using' the books!" },
    { setup: "What's the official drink of World Compass Academy?", punchline: "Blue-green Kool-Aid with white ice cubes!" },
    { setup: "Why did the World Compass Academy student bring a paintbrush to every class?", punchline: "In case they needed to add a touch of blue, green, or white to their notes!" },
    { setup: "What does Coco the Cougar say about the World Compass Academy uniforms?", punchline: "'They're grrrreat for learning and looking smart!'" },
    { setup: "What's the secret to World Compass Academy's success?", punchline: "A blend of blue knowledge, green growth, and white integrity... plus a lot of Cougar spirit!" },
    { setup: "Why did the pencil wear a tiny blue, green, and white hat at World Compass Academy?", punchline: "To show its school spirit while writing!" },
    { setup: "How does Coco the Cougar navigate the hallways of World Compass Academy so well?", punchline: "He follows the 'scent' of blue, green, and white learning!" }
];

const popCultureJokes = [
    { setup: "Why did the Creeper cross the road?", punchline: "To get to the other ssssside!" },
    { setup: "What's a Ghast's favorite country?", punchline: "The Nether-lands!" },
    { setup: "Why don't Endermen like eye contact?", punchline: "They're a little shy." },
    { setup: "What's a Pokémon's favorite type of music?", punchline: "Rock and Raichu-ll!" },
    { setup: "Why did Pikachu cross the playground?", punchline: "To get to the other slide!" },
    { setup: "What do you call a sleepy Pokémon?", punchline: "A Snorlax!" },
    { setup: "Why did Mario and Luigi bring ladders to the party?", punchline: "Because it was a multi-level event!" },
    { setup: "What's Mario's favorite type of clothing?", punchline: "Denim, denim, denim." },
    { setup: "How does Luigi answer the phone?", punchline: "Green-green!" },
    { setup: "Why did SpongeBob cross the road?", punchline: "To get to the Krusty Krab on the other side!" },
    { setup: "What's Squidward's favorite instrument?", punchline: "The clarinet, obviously, when no one is listening!" },
    { setup: "Why is Patrick so good at sleeping?", punchline: "He's a star-fish!" },
    { setup: "Why did the anime character bring a pencil to the fight?", punchline: "To draw their own conclusions!" },
    { setup: "What's a magical girl's favorite drink?", punchline: "Sparkle-ing water!" },
    { setup: "Why are shonen protagonists always hungry?", punchline: "They burn a lot of energy yelling!" },
    { setup: "What kind of car does a ninja drive?", punchline: "A Hooooonda... because they're stealthy!" },
    { setup: "Why did the chibi character get a tiny ladder?", punchline: "To reach the high shelves!" },
    { setup: "What do you call a sad Minecraft block?", punchline: "A blue-block!" },
    { setup: "Why did Steve bring a boat to the desert in Minecraft?", punchline: "He heard there was an ocean of sand!" },
    { setup: "What's a Minecraft pig's favorite karate move?", punchline: "The pork-chop!" },
    { setup: "Why was the Minecraft chicken so good at math?", punchline: "It knew how to multiply its eggs!" },
    { setup: "What did the ROBLOX character say after tripping in an obby?", punchline: "Oof! That was a blocky landing!" },
    { setup: "Why did the ROBLOX player bring a ladder to every game?", punchline: "To reach new heights of fun!" },
    { setup: "What's a ROBLOX avatar's favorite type of party?", punchline: "A block party, of course!" },
    { setup: "How do ROBLOX characters send secret messages?", punchline: "Through the chat-acter mail!" },
    { setup: "Why did the Fortnite player bring a pencil and paper to the battle?", punchline: "To draw up some victory plans!" },
    { setup: "What's a Fortnite Llama's favorite type of music?", punchline: "Anything with a good 'loot' and beat!" },
    { setup: "Why are Fortnite players so good at building?", punchline: "They always have a plan 'ramped' up!" },
    { setup: "What do you call a Fortnite dance-off in the storm?", punchline: "A shocking performance!" },
    { setup: "What’s Mario’s favorite type of pasta?", punchline: "Spaghetti with MEAT-balls!" },
    { setup: "Why did Link bring a ladder to Hyrule Field?", punchline: "He heard the Deku Scrubs were giving high-fives!" },
    { setup: "What does Tom Nook do on his day off?", punchline: "Counts his Bells and whistles!" },
    { setup: "Why is Kirby such a good friend?", punchline: "Because he's always willing to inhale your problems!" },
    { setup: "What did Princess Peach say to the Goomba?", punchline: "'You're not so tough, you're just a fun-guy!'" },
    { setup: "Why was Isabelle so tired at the Animal Crossing town hall?", punchline: "She had too many 'ruff' announcements to make!" },
    { setup: "What's Zelda's favorite instrument to 'tri'?", punchline: "The Ocarina of Time, of course!" },
    { setup: "Why did the game consoles start a band?", punchline: "They wanted to have a 'controller' jam session!" },
    { setup: "What did one game controller say to the other?", punchline: "'You push my buttons in all the right ways!'" },
    { setup: "Why don't video game consoles ever get lonely?", punchline: "Because they always have plenty of 'players'!" },
    { setup: "What's a console's favorite snack during a long game?", punchline: "Micro-chips!" },
    { setup: "Why did the video game character take a nap before the boss battle?", punchline: "To save their energy!" },
    { setup: "What’s a video game achievement's favorite subject?", punchline: "History, because it loves to be unlocked!" },
    { setup: "Why do loading screens take so long?", punchline: "They're busy drawing up the next amazing level!" },
    { setup: "What do you call a very polite video game enemy?", punchline: "A 'sir-vivor'!" },
    { setup: "Why did Woody bring a ladder to the toy box?", punchline: "To reach for the sky!" },
    { setup: "What's Buzz Lightyear's favorite planet?", punchline: "The one with the best 'space' for landing!" },
    { setup: "Why did Olaf bring a beach towel to Arendelle?", punchline: "He heard summer was finally 'chilling' out!" },
    { setup: "What's Elsa's favorite type of weather?", punchline: "A 'flurry' of fun!" },
    { setup: "What did Dory say when she forgot her lines?", punchline: "'Just keep swimming... towards the script!'" },
    { setup: "Why did Nemo cross the reef?", punchline: "To get to the other tide!" },
    { setup: "What's Timon and Pumbaa's favorite motto for homework?", punchline: "'Hakuna Matata' - it means no worries, just do your best!" },
    { setup: "Why did Simba practice his roar in the library?", punchline: "He wanted it to be a 'roaring' success, quietly!" },
    { setup: "Why did Joy and Sadness start a band?", punchline: "They wanted to make some 'emotional' music!" },
    { setup: "What's Anger's favorite game?", punchline: "Anything but 'cool' down tag!" },
    { setup: "What does Lightning McQueen say before a big race?", punchline: "'Kachow! Time to 'tire' out the competition!'" },
    { setup: "Why is Mater such a good friend?", punchline: "Because he'll always 'tow' the line for you!" },
    { setup: "Why did Moana bring a coconut to the boat?", punchline: "In case she got 'board'!" },
    { setup: "What's Maui's favorite way to travel?", punchline: "By 'hook' or by crook!" },
    { setup: "Why did Bruno try to fix the cracks in Casita?", punchline: "He wanted everything to be 'magically' perfect!" },
    { setup: "What's Mirabel's favorite thing to sew?", punchline: "A 'patchwork' of family love!" },
    { setup: "Why did the Disney princess bring a map to the ball?", punchline: "In case she lost her 'way' to Prince Charming!" },
    { setup: "What's a Pixar lamp's favorite game?", punchline: "I-spy, with its little light!" },
    { setup: "Why are Disney sidekicks so funny?", punchline: "Because they always have a 'quip' up their sleeve!" }
];
const seasonalJokes = [
    { setup: "Why do trees make good friends in spring?", punchline: "They're always ready to 'leaf' their worries behind!", tags: ["spring"] },
    // --- Spring ---
    { setup: "Why was the bee so happy in spring?", punchline: "Because everything was buzzing with life!", tags: ["spring"] },
    { setup: "What do you call a rabbit with fleas in spring?", punchline: "Bugs Bunny!", tags: ["spring", "easter"] },
    { setup: "How does a flower greet another in spring?", punchline: "'Hey bud!'", tags: ["spring"] },
    { setup: "What's a tree's favorite drink in spring?", punchline: "Root beer!", tags: ["spring"] },

    // --- Easter (can also be tagged "spring") --- // OMITTED 

    // --- St. Patrick's Day ---
    { setup: "Why shouldn't you iron a four-leaf clover?", punchline: "You don't want to press your luck!", tags: ["stpatricks"] },
    { setup: "What do you call a fake Irish stone?", punchline: "A sham-rock!", tags: ["stpatricks"] },
    { setup: "Why do leprechauns love to garden?", punchline: "They have green thumbs!", tags: ["stpatricks"] },

    // --- Valentine's Day ---
    { setup: "What did the stamp say to the envelope on Valentine's Day?", punchline: "'I'm stuck on you!'", tags: ["valentines"] },
    { setup: "What do you call a very small Valentine?", punchline: "A Valen-tiny!", tags: ["valentines"] },
    { setup: "Why is Valentine's Day the best day for a celebration?", punchline: "Because you can really heart-y!", tags: ["valentines"] },

    // --- Mother's Day ---
    { setup: "Why are moms like buttons?", punchline: "They hold everything together!", tags: ["mothersday"] },
    { setup: "What did the baby corn say to the mama corn?", punchline: "'Where's pop-corn?'", tags: ["mothersday"] },
    { setup: "Why is a mom's hug the best?", punchline: "Because it's full of 'mom'-umental love!", tags: ["mothersday"] },

    // --- Summer ---
    { setup: "What does the sun drink out of?", punchline: "Sunglasses!", tags: ["summer"] },
    { setup: "Why did the teddy bear say no to ice cream in summer?", punchline: "Because he was already stuffed!", tags: ["summer"] },
    { setup: "What do you call a fish with no eyes in the summer?", punchline: "Fsh... on vacation!", tags: ["summer"] },

    // --- Father's Day ---
    { setup: "Why did the dad bring a spare tire to the Father's Day BBQ?", punchline: "In case he got a 'flat' from eating too much!", tags: ["fathersday"] },
    { setup: "What do you call a dad who falls asleep while fishing?", punchline: "A 'nap'-perch!", tags: ["fathersday"] },
    { setup: "Why are dads so good at fixing things?", punchline: "They have a 'tool'-riffic sense of humor!", tags: ["fathersday"] },

    // --- Fall / Autumn ---
    { setup: "Why did the scarecrow win an award in the fall?", punchline: "Because he was outstanding in his 'field' of pumpkins!", tags: ["fall"] },
    { setup: "What's an autumn tree's favorite drink?", punchline: "Root beer, but with extra 'leaf'!", tags: ["fall"] },
    { setup: "What do you call a running turkey in the fall?", punchline: "Fast food!", tags: ["fall", "thanksgiving"] },

    // --- Halloween (can also be tagged "fall") ---
    { setup: "Why don't skeletons fight each other on Halloween?", punchline: "They don't have the guts!", tags: ["halloween", "fall"] },
    { setup: "What's a ghost's favorite dessert on Halloween?", punchline: "I-scream!", tags: ["halloween", "fall"] },
    { setup: "What do you call a witch's garage?", punchline: "A broom closet!", tags: ["halloween", "fall"] },

    // --- Thanksgiving (can also be tagged "fall") ---
    { setup: "Why did the turkey cross the road twice on Thanksgiving?", punchline: "To prove he wasn't chicken!", tags: ["thanksgiving", "fall"] },
    { setup: "What kind of key can't open doors but is great at Thanksgiving dinner?", punchline: "A tur-key!", tags: ["thanksgiving", "fall"] },
    { setup: "If April showers bring May flowers, what do May flowers bring?", punchline: "Pilgrims (and Thanksgiving)!", tags: ["thanksgiving", "fall"] },

    // --- Winter ---
    { setup: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman!", tags: ["winter"] },
    { setup: "How does a snowman get around?", punchline: "By 'icicle'!", tags: ["winter"] },
    { setup: "What do snowmen eat for breakfast?", punchline: "Frosted Flakes or Ice Krispies!", tags: ["winter"] },

    // --- Christmas (can also be tagged "winter") ---
    { setup: "What do you call an elf who sings?", punchline: "A wrapper!", tags: ["christmas", "winter"] },
    { setup: "Why was the Christmas tree so bad at knitting?", punchline: "It kept dropping all its needles!", tags: ["christmas", "winter"] },
    { setup: "What do you get if you cross a snowman and a vampire at Christmas?", punchline: "Frostbite!", tags: ["christmas", "winter"] },

    // --- New Year's (can also be tagged "winter") ---
    { setup: "What’s a New Year’s resolution?", punchline: "Something that goes in one year and out the other!", tags: ["newyears", "winter"] },
    { setup: "Why do we kiss on New Year's Eve?", punchline: "To start the year with a bang!", tags: ["newyearseve", "winter", "newyears"] }, // Added newyearseve tag
    { setup: "What is the problem with jogging on New Year's Eve?", punchline: "The ice falls out of your glass!", tags: ["newyearseve", "winter", "newyears"] } // Added newyearseve tag
];